"""
Database of Active Chinese Futures Contracts
Covers SHFE, DCE, CZCE, CFFEX, GFEX, INE active varieties.
Includes contract multipliers, tick sizes, standard margins, typical prices, ATR estimates, and clustering.
"""

from typing import Dict, List, Any


FUTURES_INSTRUMENTS: Dict[str, Dict[str, Any]] = {
    # ---------------- 贵金属 (Precious Metals) ----------------
    "AU": {
        "symbol": "AU",
        "name": "沪金",
        "exchange": "SHFE",
        "unit": "1000克/手",
        "multiplier": 1000.0,
        "tick_size": 0.02,
        "default_price": 929.76,
        "margin_rate": 0.16,
        "typical_atr": 19.43,
        "sector": "贵金属",
        "cluster": "precious_metals",
        "max_lots_1m": 1,
        "description": "避险核心资产，单手名义价值约93万，保证金约15万，严格限制1手"
    },
    "AG": {
        "symbol": "AG",
        "name": "沪银",
        "exchange": "SHFE",
        "unit": "15千克/手",
        "multiplier": 15.0,
        "tick_size": 1.0,
        "default_price": 7750.0,
        "margin_rate": 0.15,
        "typical_atr": 135.0,
        "sector": "贵金属",
        "cluster": "precious_metals",
        "max_lots_1m": 1,
        "description": "工业+金融双重属性，波动剧烈，单手保证金约1.7万"
    },

    # ---------------- 黑色系 (Ferrous Metals) ----------------
    "RB": {
        "symbol": "RB",
        "name": "螺纹钢",
        "exchange": "SHFE",
        "unit": "10吨/手",
        "multiplier": 10.0,
        "tick_size": 1.0,
        "default_price": 3400.0,
        "margin_rate": 0.10,
        "typical_atr": 55.0,
        "sector": "黑色系",
        "cluster": "ferrous_construction",
        "max_lots_1m": 8,
        "description": "建材核心品种，流动性极佳，与地产周期高度共振"
    },
    "HC": {
        "symbol": "HC",
        "name": "热卷",
        "exchange": "SHFE",
        "unit": "10吨/手",
        "multiplier": 10.0,
        "tick_size": 1.0,
        "default_price": 3500.0,
        "margin_rate": 0.10,
        "typical_atr": 60.0,
        "sector": "黑色系",
        "cluster": "ferrous_construction",
        "max_lots_1m": 8,
        "description": "工业板材代表，与螺纹钢价差联动紧密"
    },
    "I": {
        "symbol": "I",
        "name": "铁矿石",
        "exchange": "DCE",
        "unit": "100吨/手",
        "multiplier": 100.0,
        "tick_size": 0.5,
        "default_price": 780.0,
        "margin_rate": 0.14,
        "typical_atr": 18.0,
        "sector": "黑色系",
        "cluster": "ferrous_construction",
        "max_lots_1m": 3,
        "description": "高弹性外盘联动品种，一手名义价值约7.8万，单点波动大"
    },
    "J": {
        "symbol": "J",
        "name": "焦炭",
        "exchange": "DCE",
        "unit": "100吨/手",
        "multiplier": 100.0,
        "tick_size": 0.5,
        "default_price": 1950.0,
        "margin_rate": 0.15,
        "typical_atr": 45.0,
        "sector": "黑色系",
        "cluster": "ferrous_construction",
        "max_lots_1m": 2,
        "description": "煤焦钢产业链中游，保证金占用大，价格波动率高"
    },
    "JM": {
        "symbol": "JM",
        "name": "焦煤",
        "exchange": "DCE",
        "unit": "60吨/手",
        "multiplier": 60.0,
        "tick_size": 0.5,
        "default_price": 1280.0,
        "margin_rate": 0.15,
        "typical_atr": 32.0,
        "sector": "黑色系",
        "cluster": "ferrous_construction",
        "max_lots_1m": 2,
        "description": "上游高弹性原料，易受安全检查及政策情绪扰动"
    },
    "SS": {
        "symbol": "SS",
        "name": "不锈钢",
        "exchange": "SHFE",
        "unit": "5吨/手",
        "multiplier": 5.0,
        "tick_size": 5.0,
        "default_price": 13800.0,
        "margin_rate": 0.10,
        "typical_atr": 180.0,
        "sector": "黑色系",
        "cluster": "ferrous_construction",
        "max_lots_1m": 4,
        "description": "特钢板材，兼具镍产业链与钢材需求特征"
    },

    # ---------------- 有色金属 (Base Metals) ----------------
    "CU": {
        "symbol": "CU",
        "name": "沪铜",
        "exchange": "SHFE",
        "unit": "5吨/手",
        "multiplier": 5.0,
        "tick_size": 10.0,
        "default_price": 79000.0,
        "margin_rate": 0.11,
        "typical_atr": 950.0,
        "sector": "有色金属",
        "cluster": "base_metals",
        "max_lots_1m": 1,
        "description": "大宗之王，单手名义价值近40万，100万账户严格限制1手"
    },
    "AL": {
        "symbol": "AL",
        "name": "沪铝",
        "exchange": "SHFE",
        "unit": "5吨/手",
        "multiplier": 5.0,
        "tick_size": 5.0,
        "default_price": 20500.0,
        "margin_rate": 0.10,
        "typical_atr": 260.0,
        "sector": "有色金属",
        "cluster": "base_metals",
        "max_lots_1m": 3,
        "description": "高能耗冶炼金属，受电力成本与氧化铝价格影响深远"
    },
    "ZN": {
        "symbol": "ZN",
        "name": "沪锌",
        "exchange": "SHFE",
        "unit": "5吨/手",
        "multiplier": 5.0,
        "tick_size": 5.0,
        "default_price": 23500.0,
        "margin_rate": 0.10,
        "typical_atr": 380.0,
        "sector": "有色金属",
        "cluster": "base_metals",
        "max_lots_1m": 2,
        "description": "镀锌下游受基建汽车拉动，冶炼加工费TC敏感"
    },
    "PB": {
        "symbol": "PB",
        "name": "沪铅",
        "exchange": "SHFE",
        "unit": "5吨/手",
        "multiplier": 5.0,
        "tick_size": 5.0,
        "default_price": 16800.0,
        "margin_rate": 0.10,
        "typical_atr": 220.0,
        "sector": "有色金属",
        "cluster": "base_metals",
        "max_lots_1m": 3,
        "description": "铅酸蓄电池主导，波动相对平缓"
    },
    "NI": {
        "symbol": "NI",
        "name": "沪镍",
        "exchange": "SHFE",
        "unit": "1吨/手",
        "multiplier": 1.0,
        "tick_size": 10.0,
        "default_price": 128000.0,
        "margin_rate": 0.13,
        "typical_atr": 2400.0,
        "sector": "有色金属",
        "cluster": "base_metals",
        "max_lots_1m": 1,
        "description": "高波动小金属，单手1吨，单点跳动10元，跳空风险高"
    },
    "SN": {
        "symbol": "SN",
        "name": "沪锡",
        "exchange": "SHFE",
        "unit": "1吨/手",
        "multiplier": 1.0,
        "tick_size": 10.0,
        "default_price": 265000.0,
        "margin_rate": 0.14,
        "typical_atr": 4500.0,
        "sector": "有色金属",
        "cluster": "base_metals",
        "max_lots_1m": 1,
        "description": "电子半导体焊料金属，单手名义价值高，极端限价保护严格"
    },
    "AO": {
        "symbol": "AO",
        "name": "氧化铝",
        "exchange": "SHFE",
        "unit": "20吨/手",
        "multiplier": 20.0,
        "tick_size": 1.0,
        "default_price": 4100.0,
        "margin_rate": 0.12,
        "typical_atr": 95.0,
        "sector": "有色金属",
        "cluster": "base_metals",
        "max_lots_1m": 4,
        "description": "铝产业链上游矿石原料，供需错配行情波动大"
    },

    # ---------------- 化工建材与能源 (Chemicals & Energy) ----------------
    "SA": {
        "symbol": "SA",
        "name": "纯碱",
        "exchange": "CZCE",
        "unit": "20吨/手",
        "multiplier": 20.0,
        "tick_size": 1.0,
        "default_price": 1450.0,
        "margin_rate": 0.12,
        "typical_atr": 38.0,
        "sector": "化工能源",
        "cluster": "ferrous_construction",  # 强地产玻璃链
        "max_lots_1m": 6,
        "description": "玻璃产业链核心原料，高投机度，与建材及黑色联动"
    },
    "FG": {
        "symbol": "FG",
        "name": "玻璃",
        "exchange": "CZCE",
        "unit": "20吨/手",
        "multiplier": 20.0,
        "tick_size": 1.0,
        "default_price": 1250.0,
        "margin_rate": 0.12,
        "typical_atr": 32.0,
        "sector": "化工能源",
        "cluster": "ferrous_construction",  # 强地产玻璃链
        "max_lots_1m": 8,
        "description": "地产竣工端核心标的，库存累积敏感"
    },
    "MA": {
        "symbol": "MA",
        "name": "甲醇",
        "exchange": "CZCE",
        "unit": "10吨/手",
        "multiplier": 10.0,
        "tick_size": 1.0,
        "default_price": 2480.0,
        "margin_rate": 0.10,
        "typical_atr": 45.0,
        "sector": "化工能源",
        "cluster": "energy_chemicals",
        "max_lots_1m": 6,
        "description": "煤化工龙头品种，流动性充足，MTO制烯烃需求枢纽"
    },
    "PP": {
        "symbol": "PP",
        "name": "聚丙烯",
        "exchange": "DCE",
        "unit": "5吨/手",
        "multiplier": 5.0,
        "tick_size": 1.0,
        "default_price": 7450.0,
        "margin_rate": 0.10,
        "typical_atr": 95.0,
        "sector": "化工能源",
        "cluster": "energy_chemicals",
        "max_lots_1m": 6,
        "description": "聚烯烃塑料板块代表，成本受原油与煤炭双向影响"
    },
    "L": {
        "symbol": "L",
        "name": "塑料(LLDPE)",
        "exchange": "DCE",
        "unit": "5吨/手",
        "multiplier": 5.0,
        "tick_size": 1.0,
        "default_price": 8100.0,
        "margin_rate": 0.10,
        "typical_atr": 105.0,
        "sector": "化工能源",
        "cluster": "energy_chemicals",
        "max_lots_1m": 6,
        "description": "农膜与包装主料，与PP高度相关"
    },
    "V": {
        "symbol": "V",
        "name": "PVC",
        "exchange": "DCE",
        "unit": "5吨/手",
        "multiplier": 5.0,
        "tick_size": 1.0,
        "default_price": 5300.0,
        "margin_rate": 0.10,
        "typical_atr": 85.0,
        "sector": "化工能源",
        "cluster": "ferrous_construction",
        "max_lots_1m": 6,
        "description": "电石法聚氯乙烯，管材型材用于建筑管道"
    },
    "TA": {
        "symbol": "TA",
        "name": "PTA",
        "exchange": "CZCE",
        "unit": "5吨/手",
        "multiplier": 5.0,
        "tick_size": 2.0,
        "default_price": 5050.0,
        "margin_rate": 0.10,
        "typical_atr": 75.0,
        "sector": "化工能源",
        "cluster": "energy_chemicals",
        "max_lots_1m": 6,
        "description": "聚酯化纤上游原料，原油PX成本驱动明显"
    },
    "EG": {
        "symbol": "EG",
        "name": "乙二醇",
        "exchange": "DCE",
        "unit": "10吨/手",
        "multiplier": 10.0,
        "tick_size": 1.0,
        "default_price": 4550.0,
        "margin_rate": 0.10,
        "typical_atr": 65.0,
        "sector": "化工能源",
        "cluster": "energy_chemicals",
        "max_lots_1m": 6,
        "description": "聚酯双原料之一，煤制与油制工艺博弈"
    },
    "EB": {
        "symbol": "EB",
        "name": "苯乙烯",
        "exchange": "DCE",
        "unit": "5吨/手",
        "multiplier": 5.0,
        "tick_size": 1.0,
        "default_price": 8700.0,
        "margin_rate": 0.11,
        "typical_atr": 150.0,
        "sector": "化工能源",
        "cluster": "energy_chemicals",
        "max_lots_1m": 4,
        "description": "纯苯与乙烯下游，波动率通常高于一般塑料"
    },
    "UR": {
        "symbol": "UR",
        "name": "尿素",
        "exchange": "CZCE",
        "unit": "20吨/手",
        "multiplier": 20.0,
        "tick_size": 1.0,
        "default_price": 1900.0,
        "margin_rate": 0.11,
        "typical_atr": 40.0,
        "sector": "化工能源",
        "cluster": "energy_chemicals",
        "max_lots_1m": 5,
        "description": "农资化肥核心原料，兼具农业需求与煤炭成本周期"
    },
    "BR": {
        "symbol": "BR",
        "name": "丁二烯橡胶",
        "exchange": "SHFE",
        "unit": "5吨/手",
        "multiplier": 5.0,
        "tick_size": 5.0,
        "default_price": 14500.0,
        "margin_rate": 0.12,
        "typical_atr": 280.0,
        "sector": "化工能源",
        "cluster": "energy_chemicals",
        "max_lots_1m": 2,
        "description": "合成橡胶代表，原油丁二烯原料端扰动大"
    },
    "SC": {
        "symbol": "SC",
        "name": "原油",
        "exchange": "INE",
        "unit": "1000桶/手",
        "multiplier": 1000.0,
        "tick_size": 0.1,
        "default_price": 540.0,
        "margin_rate": 0.12,
        "typical_atr": 12.0,
        "sector": "化工能源",
        "cluster": "energy_chemicals",
        "max_lots_1m": 1,
        "description": "全球宏观与地缘政治风向标，单手名义价值50万+"
    },
    "FU": {
        "symbol": "FU",
        "name": "燃料油",
        "exchange": "SHFE",
        "unit": "10吨/手",
        "multiplier": 10.0,
        "tick_size": 1.0,
        "default_price": 3100.0,
        "margin_rate": 0.15,
        "typical_atr": 65.0,
        "sector": "化工能源",
        "cluster": "energy_chemicals",
        "max_lots_1m": 4,
        "description": "高硫船燃代表，上期所近日常调保至18%"
    },
    "PG": {
        "symbol": "PG",
        "name": "LPG(液化石油气)",
        "exchange": "DCE",
        "unit": "20吨/手",
        "multiplier": 20.0,
        "tick_size": 1.0,
        "default_price": 4450.0,
        "margin_rate": 0.12,
        "typical_atr": 95.0,
        "sector": "化工能源",
        "cluster": "energy_chemicals",
        "max_lots_1m": 2,
        "description": "燃烧与化工深加工原料，受国际现货CP价格主导"
    },
    "BU": {
        "symbol": "BU",
        "name": "沥青",
        "exchange": "SHFE",
        "unit": "10吨/手",
        "multiplier": 10.0,
        "tick_size": 1.0,
        "default_price": 3450.0,
        "margin_rate": 0.11,
        "typical_atr": 55.0,
        "sector": "化工能源",
        "cluster": "ferrous_construction",
        "max_lots_1m": 4,
        "description": "道路铺设建材，与重油炼化紧密相连"
    },

    # ---------------- 农产品与养殖 (Agriculture & Livestock) ----------------
    "M": {
        "symbol": "M",
        "name": "豆粕",
        "exchange": "DCE",
        "unit": "10吨/手",
        "multiplier": 10.0,
        "tick_size": 1.0,
        "default_price": 3050.0,
        "margin_rate": 0.09,
        "typical_atr": 45.0,
        "sector": "农产品",
        "cluster": "agri_oils_softs",
        "max_lots_1m": 6,
        "description": "蛋白饲料基准，美豆USDA报告与国内压榨开工决定供需"
    },
    "RM": {
        "symbol": "RM",
        "name": "菜粕",
        "exchange": "CZCE",
        "unit": "10吨/手",
        "multiplier": 10.0,
        "tick_size": 1.0,
        "default_price": 2400.0,
        "margin_rate": 0.10,
        "typical_atr": 50.0,
        "sector": "农产品",
        "cluster": "agri_oils_softs",
        "max_lots_1m": 6,
        "description": "水产饲料蛋白，弹性大于豆粕"
    },
    "Y": {
        "symbol": "Y",
        "name": "豆油",
        "exchange": "DCE",
        "unit": "10吨/手",
        "multiplier": 10.0,
        "tick_size": 2.0,
        "default_price": 8150.0,
        "margin_rate": 0.10,
        "typical_atr": 130.0,
        "sector": "农产品",
        "cluster": "agri_oils_softs",
        "max_lots_1m": 3,
        "description": "三大油脂核心成员，受生物柴油与餐饮消费牵引"
    },
    "P": {
        "symbol": "P",
        "name": "棕榈油",
        "exchange": "DCE",
        "unit": "10吨/手",
        "multiplier": 10.0,
        "tick_size": 2.0,
        "default_price": 8900.0,
        "margin_rate": 0.11,
        "typical_atr": 180.0,
        "sector": "农产品",
        "cluster": "agri_oils_softs",
        "max_lots_1m": 3,
        "description": "高弹性进口植物油，印尼马来产地产量与出口政策驱动"
    },
    "OI": {
        "symbol": "OI",
        "name": "菜油",
        "exchange": "CZCE",
        "unit": "10吨/手",
        "multiplier": 10.0,
        "tick_size": 1.0,
        "default_price": 9300.0,
        "margin_rate": 0.10,
        "typical_atr": 160.0,
        "sector": "农产品",
        "cluster": "agri_oils_softs",
        "max_lots_1m": 3,
        "description": "高品质植物油，与豆棕套利资金深度交织"
    },
    "CF": {
        "symbol": "CF",
        "name": "棉花",
        "exchange": "CZCE",
        "unit": "5吨/手",
        "multiplier": 5.0,
        "tick_size": 5.0,
        "default_price": 14200.0,
        "margin_rate": 0.10,
        "typical_atr": 190.0,
        "sector": "农产品",
        "cluster": "agri_oils_softs",
        "max_lots_1m": 4,
        "description": "纺织服装产业链源头，兼具农情天气与外贸出口导向"
    },
    "SR": {
        "symbol": "SR",
        "name": "白糖",
        "exchange": "CZCE",
        "unit": "10吨/手",
        "multiplier": 10.0,
        "tick_size": 1.0,
        "default_price": 5900.0,
        "margin_rate": 0.10,
        "typical_atr": 65.0,
        "sector": "农产品",
        "cluster": "agri_oils_softs",
        "max_lots_1m": 4,
        "description": "软商品经典品种，巴西甘蔗制糖比与印度榨季是关键"
    },
    "AP": {
        "symbol": "AP",
        "name": "苹果",
        "exchange": "CZCE",
        "unit": "10吨/手",
        "multiplier": 10.0,
        "tick_size": 1.0,
        "default_price": 7200.0,
        "margin_rate": 0.13,
        "typical_atr": 140.0,
        "sector": "农产品",
        "cluster": "agri_oils_softs",
        "max_lots_1m": 3,
        "description": "鲜果冷库仓单博弈，时令性极强，高波动品种"
    },
    "CJ": {
        "symbol": "CJ",
        "name": "红枣",
        "exchange": "CZCE",
        "unit": "5吨/手",
        "multiplier": 5.0,
        "tick_size": 5.0,
        "default_price": 9500.0,
        "margin_rate": 0.12,
        "typical_atr": 160.0,
        "sector": "农产品",
        "cluster": "agri_oils_softs",
        "max_lots_1m": 4,
        "description": "新疆灰枣产销两地博弈，阶段性单边行情鲜明"
    },
    "JD": {
        "symbol": "JD",
        "name": "鸡蛋",
        "exchange": "DCE",
        "unit": "5吨/手",
        "multiplier": 5.0,
        "tick_size": 1.0,
        "default_price": 3600.0,
        "margin_rate": 0.10,
        "typical_atr": 65.0,
        "sector": "农产品",
        "cluster": "agri_oils_softs",
        "max_lots_1m": 5,
        "description": "生鲜高频消费品，产蛋鸡存栏与淘鸡节奏主导"
    },
    "LH": {
        "symbol": "LH",
        "name": "生猪",
        "exchange": "DCE",
        "unit": "16吨/手",
        "multiplier": 16.0,
        "tick_size": 5.0,
        "default_price": 14500.0,
        "margin_rate": 0.12,
        "typical_atr": 260.0,
        "sector": "农产品",
        "cluster": "agri_oils_softs",
        "max_lots_1m": 1,
        "description": "猪周期大品种，一手16吨名义价值23万+，严格控1手"
    },

    # ---------------- 新能源与新兴产业 (New Energy & Innovative) ----------------
    "LC": {
        "symbol": "LC",
        "name": "碳酸锂",
        "exchange": "GFEX",
        "unit": "1吨/手",
        "multiplier": 1.0,
        "tick_size": 50.0,
        "default_price": 76500.0,
        "margin_rate": 0.15,
        "typical_atr": 2200.0,
        "sector": "新能源",
        "cluster": "new_energy_special",
        "max_lots_1m": 2,
        "description": "新能源动力电池白色石油，供需过剩周期寻底，极高投机弹性"
    },
    "SI": {
        "symbol": "SI",
        "name": "工业硅",
        "exchange": "GFEX",
        "unit": "5吨/手",
        "multiplier": 5.0,
        "tick_size": 5.0,
        "default_price": 10500.0,
        "margin_rate": 0.11,
        "typical_atr": 240.0,
        "sector": "新能源",
        "cluster": "new_energy_special",
        "max_lots_1m": 4,
        "description": "光伏多晶硅与有机硅上游，广期所首个明星品种"
    },
    "EC": {
        "symbol": "EC",
        "name": "集运指数(欧线)",
        "exchange": "INE",
        "unit": "50元/点",
        "multiplier": 50.0,
        "tick_size": 0.1,
        "default_price": 2350.0,
        "margin_rate": 0.20,
        "typical_atr": 90.0,
        "sector": "航运指数",
        "cluster": "new_energy_special",
        "max_lots_1m": 1,
        "description": "地缘红海局势风向标，交易所调保频繁，单手极高风险"
    },

    # ---------------- 金融期货 (Financial Futures) ----------------
    "IF": {
        "symbol": "IF",
        "name": "沪深300股指",
        "exchange": "CFFEX",
        "unit": "300元/点",
        "multiplier": 300.0,
        "tick_size": 0.2,
        "default_price": 3850.0,
        "margin_rate": 0.12,
        "typical_atr": 45.0,
        "sector": "金融期货",
        "cluster": "financial",
        "max_lots_1m": 1,
        "description": "大盘蓝筹股指，一手名义价值115万，100万仅限极低频或对冲"
    },
    "IC": {
        "symbol": "IC",
        "name": "中证500股指",
        "exchange": "CFFEX",
        "unit": "200元/点",
        "multiplier": 200.0,
        "tick_size": 0.2,
        "default_price": 5400.0,
        "margin_rate": 0.12,
        "typical_atr": 75.0,
        "sector": "金融期货",
        "cluster": "financial",
        "max_lots_1m": 1,
        "description": "中盘成长风格，一手名义价值108万"
    },
    "IM": {
        "symbol": "IM",
        "name": "中证1000股指",
        "exchange": "CFFEX",
        "unit": "200元/点",
        "multiplier": 200.0,
        "tick_size": 0.2,
        "default_price": 5600.0,
        "margin_rate": 0.15,
        "typical_atr": 95.0,
        "sector": "金融期货",
        "cluster": "financial",
        "max_lots_1m": 1,
        "description": "小盘微盘高弹性风格，量化CTA与指增主要对冲标的"
    },
    "T": {
        "symbol": "T",
        "name": "10年期国债",
        "exchange": "CFFEX",
        "unit": "10000元/点",
        "multiplier": 10000.0,
        "tick_size": 0.005,
        "default_price": 106.5,
        "margin_rate": 0.02,
        "typical_atr": 0.18,
        "sector": "金融期货",
        "cluster": "financial",
        "max_lots_1m": 2,
        "description": "无风险利率基准，杠杆倍数高但价格日内波动极小"
    }
}


def get_all_instruments() -> List[Dict[str, Any]]:
    """Returns list of all instruments."""
    return list(FUTURES_INSTRUMENTS.values())


def get_instrument(symbol: str) -> Dict[str, Any]:
    """Fetch contract spec by symbol (case insensitive)."""
    sym = symbol.upper().strip()
    if sym in FUTURES_INSTRUMENTS:
        return FUTURES_INSTRUMENTS[sym]
    # Fallback default
    return {
        "symbol": sym,
        "name": sym,
        "exchange": "CUSTOM",
        "unit": "10单位/手",
        "multiplier": 10.0,
        "tick_size": 1.0,
        "default_price": 2000.0,
        "margin_rate": 0.12,
        "typical_atr": 40.0,
        "sector": "其他",
        "cluster": "other",
        "max_lots_1m": 2,
        "description": "自定义品种"
    }


def get_sectors() -> List[str]:
    """Returns sorted unique sector names."""
    sectors = set(inst["sector"] for inst in FUTURES_INSTRUMENTS.values())
    return sorted(list(sectors))


def get_clusters() -> Dict[str, str]:
    """Returns cluster code to human readable name mapping."""
    return {
        "ferrous_construction": "黑色与建材共振链 (JM/RB/HC/I/J/SS/SA/FG/V/BU)",
        "precious_metals": "贵金属避险链 (AU/AG)",
        "base_metals": "有色工业金属链 (CU/AL/ZN/PB/NI/SN/AO)",
        "energy_chemicals": "能源与化工链 (SC/FU/PG/MA/PP/L/TA/EG/EB/UR/BR)",
        "agri_oils_softs": "农产品与油脂生鲜链 (M/RM/Y/P/OI/CF/SR/CJ/JD/LH/AP)",
        "new_energy_special": "新能源与航运创新链 (LC/SI/EC)",
        "financial": "金融股指与国债链 (IF/IC/IM/T)"
    }
